.PHONY: help install lint format typecheck test check clean pre-commit-install pre-commit-run

help:  ## Show this help.
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

install:  ## Install all dependencies including dev tools.
	uv sync --all-groups

lint:  ## Run Ruff lint and format check.
	uv run ruff check .
	uv run ruff format --check .

format:  ## Auto-fix lint and format code.
	uv run ruff check --fix .
	uv run ruff format .

typecheck:  ## Run mypy strict type-check.
	uv run mypy

test:  ## Run pytest with coverage (unit + integration; needs Docker for integration).
	uv run pytest

test-unit:  ## Run only unit tests (no Docker required).
	uv run pytest -m "not integration"

test-integration:  ## Run only integration tests (requires Docker daemon).
	uv run pytest -m integration

check: lint typecheck test  ## Run all quality gates (lint + types + tests).

db-up:  ## Start Postgres in the background.
	docker compose up -d db

db-down:  ## Stop Postgres and remove the container.
	docker compose down

db-migrate:  ## Apply Alembic migrations against the running Postgres.
	uv run alembic upgrade head

db-revision:  ## Create a new autogenerated migration. Usage: make db-revision m="message"
	uv run alembic revision --autogenerate -m "$(m)"

db-reset: db-down db-up  ## Recreate the database from scratch.
	@echo "Waiting for Postgres..." && sleep 3
	uv run alembic upgrade head

train:  ## Train the baseline Isolation Forest on synthetic data.
	uv run python scripts/train_baseline.py

model-card:  ## (Re-)generate docs/model-cards/baseline.md from the latest artifact.
	uv run python scripts/generate_model_card.py

eval-skab:  ## Download SKAB on first run and evaluate the baseline detector against it.
	uv run python scripts/evaluate_skab.py

demo-preview:  ## Re-render docs/assets/dashboard-preview.png.
	uv run python scripts/render_demo_preview.py

stack-up:  ## docker compose up the full stack (build + detach).
	docker compose up -d --build

stack-down:  ## docker compose down.
	docker compose down

pre-commit-install:  ## Install pre-commit git hooks.
	uv run pre-commit install

pre-commit-run:  ## Run all pre-commit hooks on every file.
	uv run pre-commit run --all-files

clean:  ## Remove caches and build artifacts.
	rm -rf .pytest_cache .mypy_cache .ruff_cache .coverage htmlcov coverage.xml dist build
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
	find . -type d -name '*.egg-info' -prune -exec rm -rf {} +
