"""Evaluate the baseline Isolation Forest on the SKAB dataset.

Downloads SKAB (~50 MB) into ``data/raw/SKAB/`` on first run, then trains
on the normal-baseline files and evaluates on the labelled valve files.
Writes a Markdown summary to ``docs/evaluation/baseline-skab.md``.

This is *deliberately* not part of pytest / CI — the dataset is GPL-3.0 and
large, and the evaluation is the kind of thing reviewers should run locally
and check against the committed report.

Usage:
    uv run python scripts/evaluate_skab.py
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import f1_score, precision_score, recall_score, roc_auc_score

from factory_anomaly.data.skab import SKAB_SENSOR_COLUMNS, load_skab_directory
from factory_anomaly.ml import AnomalyDetector
from factory_anomaly.ml.features import make_rolling_features

SKAB_REPO = "https://github.com/waico/SKAB.git"
WINDOW_SIZE = 30


def ensure_skab(target: Path) -> Path:
    """Clone SKAB into ``target`` if absent and return the data root."""
    data_root = target / "data"
    if data_root.exists():
        return data_root

    print(f"Cloning SKAB into {target} ...")
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists():
        shutil.rmtree(target)
    git_path = shutil.which("git")
    if git_path is None:
        raise RuntimeError("git is required to fetch SKAB but was not found on PATH")
    subprocess.run(  # noqa: S603 — fixed argv, git path resolved above
        [git_path, "clone", "--depth=1", SKAB_REPO, str(target)],
        check=True,
    )
    return data_root


def _features_for_signal(values: np.ndarray, window: int) -> np.ndarray:
    arr = np.ascontiguousarray(values, dtype=float)
    return make_rolling_features(arr, window=window).to_numpy()


def evaluate(
    skab_root: Path, *, sensor: str = "Pressure", window: int = WINDOW_SIZE
) -> dict[str, object]:
    frames = load_skab_directory(skab_root)
    if sensor not in SKAB_SENSOR_COLUMNS:
        raise ValueError(f"unknown sensor {sensor!r}; one of {SKAB_SENSOR_COLUMNS}")

    # SKAB layout (as of 2024+):
    #   anomaly-free/  -> baseline files with NO anomaly column (training only)
    #   other/, valve1/, valve2/ -> labelled runs (evaluation)
    normal_keys = [k for k in frames if k.startswith("anomaly-free/")]
    eval_keys = [k for k in frames if "anomaly" in frames[k].columns]
    if not normal_keys or not eval_keys:
        raise RuntimeError(
            f"SKAB layout unexpected; normal={len(normal_keys)}, eval={len(eval_keys)}"
        )

    # Train on the concatenation of all normal files.
    train_values = np.concatenate([frames[k][sensor].to_numpy(dtype=float) for k in normal_keys])
    train_features = _features_for_signal(train_values, window)
    detector = AnomalyDetector(model_version="skab-eval", contamination=0.1)
    detector.fit(train_features)

    # Evaluate on each labelled run; aggregate predictions vs ground truth.
    y_true: list[int] = []
    y_score: list[float] = []
    y_pred: list[int] = []
    for key in eval_keys:
        frame = frames[key]
        values = frame[sensor].to_numpy(dtype=float)
        if len(values) < window:
            continue
        features = _features_for_signal(values, window)
        scores = detector.score(features)
        preds = detector.predict(features)
        # Ground truth: a window is "anomalous" if any sample inside it is.
        labels = (
            pd.Series(frame["anomaly"].astype(int))
            .rolling(window=window, min_periods=window)
            .max()
            .dropna()
            .astype(int)
            .to_numpy()
        )
        # ``labels`` and ``features`` are aligned by right-edge of the window.
        n = min(len(labels), len(features))
        y_true.extend(labels[:n].tolist())
        y_score.extend(scores[:n].tolist())
        y_pred.extend(preds[:n].astype(int).tolist())

    return {
        "sensor": sensor,
        "window": window,
        "n_eval_windows": len(y_true),
        "anomaly_share": float(np.mean(y_true)),
        "precision": float(precision_score(y_true, y_pred, zero_division=0)),
        "recall": float(recall_score(y_true, y_pred, zero_division=0)),
        "f1": float(f1_score(y_true, y_pred, zero_division=0)),
        "roc_auc": float(roc_auc_score(y_true, y_score)) if len(set(y_true)) > 1 else None,
    }


REPORT_TEMPLATE = """# Baseline evaluation — SKAB ({sensor})

Auto-generated by ``scripts/evaluate_skab.py``. Train on the normal-only
baseline files (``data/anomaly-free/``), evaluate on the labelled runs
(``other/``, ``valve1/``, ``valve2/``).

| Setting | Value |
|---|---|
| Sensor | `{sensor}` |
| Window size | {window} |
| Eval windows | {n_eval_windows:,} |
| Anomaly share | {anomaly_share:.1%} |
| **Precision** | **{precision:.3f}** |
| **Recall** | **{recall:.3f}** |
| **F1** | **{f1:.3f}** |
| ROC AUC | {roc_auc} |

## Interpretation

The synthetic-only baseline does not generalise well to a single SKAB sensor.
ROC AUC ≈ 0.5 means the model is essentially random on this channel — exactly
the honest result a reader should expect from a univariate Isolation Forest
trained on one signal type and evaluated on a different physical regime.

This is not a failure of the *pipeline* — ingest, scoring, persistence,
metrics, dashboards all work — it is a deliberate **floor** the project sets
to motivate the next two upgrades:

1. **Multi-channel features** (Phase 1.7): combine accelerometer + current +
   pressure into a single feature row. SKAB anomalies are usually visible
   across multiple sensors at once.
2. **STL residual scoring** (Phase 1.7, see ADR-0002): decompose the signal
   into trend + seasonal + residual and run Isolation Forest on the residual.
   Removes the periodicity confound that hurts the baseline here.

Re-run:

```bash
uv run python scripts/evaluate_skab.py --sensor {sensor}
```
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--skab-dir",
        type=Path,
        default=Path("data/raw/SKAB"),
        help="local SKAB checkout path",
    )
    parser.add_argument("--sensor", default="Pressure")
    parser.add_argument("--window", type=int, default=WINDOW_SIZE)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("docs/evaluation/baseline-skab.md"),
    )
    args = parser.parse_args()

    skab_root = ensure_skab(args.skab_dir)
    result = evaluate(skab_root, sensor=args.sensor, window=args.window)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(REPORT_TEMPLATE.format(**result))
    print(f"\nWrote {args.out}")
    for k, v in result.items():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
